allowBuilds:
  "@sentry/cli": true
  cpu-features: set this to true or false
  esbuild: set this to true or false
  msw: true
  protobufjs: set this to true or false
  sharp: true
  ssh2: set this to true or false
