sonar.projectKey=porteken_pet-app
sonar.organization=porteken
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/__tests__/**,**/*.test.*,src/components/**,src/config/**,src/instrumentation-client.ts,src/instrumentation.ts,src/proxy.ts,src/testing/**,**/*types.ts,**/constants.ts,tests/**,eslint.config.mjs,next.config.ts,pnpm-lock.yaml,package.json,playwright.config.ts,postcss.config.mjs,sentry.edge.config.ts,sentry.server.config.ts,tsconfig.json,vitest.config.ts,vitest.integration.config.ts,vitest.setup.ts
sonar.exclusions=src/components/ui/**
sonar.qualitygate.wait=true

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=pet-app
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
